namespace WarhammerApp.API.Entities.Models.Enums
{
    public enum BuiltInSkills : byte
    {
        Hiding = 1,
        Rowing = 2,
        Valuation = 3,
        Hypnosis = 4,
        Ventriloquism = 5,
        ReadingAndWriting = 6,
        LipReading = 7,
        Talk = 8,
        Bargaining = 9,
        Intimidation = 10,
        TheArtOfSurvival = 11,
        Makeup = 12,
        Sneaking = 13,
        Searching = 14,
        Convincing = 15,
        Carriage = 16,
        Swimming = 17,
        Gossip = 18,
        AnimalCare = 19,
        StrongHead = 20,
        Horsemanship = 21,
        Gambling = 22,
        Commanding = 23,
        Treatment = 24,
        Observation = 25,
        Navigation = 26,
        Climbing = 27,
        OpeningLocks = 28,
        Taming = 29,
        Sailing = 30,
        NimbleFingers = 31,
        MagicDetection = 32,
        PoisionBrewing = 33,
        SettingTraps = 34,
        Tracking = 35,
        MisticLanguage = 36,
        Torture = 37,
        MagicEntwining = 38,
        Dodge = 39,
        SecretMarks = 40,
        SecretLanguage = 41,
        Knowledge = 42,
        Craft = 43,
        Prestidigitation = 44,
        Language = 45,
        Science = 46,
        Training = 47,
        TracesTracking = 48
    }
}