// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarhammerProfessionApp.Entities;

namespace WarhammerProfessionApp.Migrations
{
    [DbContext(typeof(ProfessionsContext))]
    [Migration("20200403204123_SchemaInitialization")]
    partial class SchemaInitialization
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasImpactOnStatictics")
                        .HasColumnType("bit");

                    b.Property<int?>("ImpactValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte?>("ValueToAlter")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.AdditionalCharacterValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("AdditionalCharacterValue");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CurrentProfessionId")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceSummary")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceUsed")
                        .HasColumnType("int");

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Race")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentProfessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.CharacterAbility", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("AbilityId")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("CharacterAbility");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.CharacterItem", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterItem");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.CharacterProfession", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessionId")
                        .HasColumnType("int");

                    b.Property<byte>("Order")
                        .HasColumnType("tinyint");

                    b.HasKey("CharacterId", "ProfessionId");

                    b.HasIndex("ProfessionId");

                    b.ToTable("CharacterProfession");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.CharacterSkill", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint");

                    b.HasKey("CharacterId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("CharacterSkill");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.CharacterStatistic", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<byte>("StatisticId")
                        .HasColumnType("tinyint");

                    b.Property<int>("BaseValue")
                        .HasColumnType("int");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "StatisticId");

                    b.HasIndex("StatisticId");

                    b.ToTable("CharacterStatistic");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.ExperienceAdditionalCharacterValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("ExperienceAdditionalCharacterValue");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("ItemType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<byte>("Rarity")
                        .HasColumnType("tinyint");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionAbilities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProfessionId")
                        .HasColumnType("int");

                    b.Property<byte>("Quantity")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionId");

                    b.ToTable("ProfessionAbilities");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionAbility", b =>
                {
                    b.Property<int>("ProfessionAbilitiesId")
                        .HasColumnType("int");

                    b.Property<int>("AbilityId")
                        .HasColumnType("int");

                    b.HasKey("ProfessionAbilitiesId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.ToTable("ProfessionAbility");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionItem", b =>
                {
                    b.Property<int>("ProfessionsItemId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProfessionsItemId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("ProfessionItem");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProfessionId")
                        .HasColumnType("int");

                    b.Property<byte>("Quantity")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionId");

                    b.ToTable("ProfessionItems");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionProfession", b =>
                {
                    b.Property<int>("EntranceProfessionId")
                        .HasColumnType("int");

                    b.Property<int>("OutputProfessionId")
                        .HasColumnType("int");

                    b.HasKey("EntranceProfessionId", "OutputProfessionId");

                    b.HasIndex("OutputProfessionId");

                    b.ToTable("ProfessionProfession");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionSkill", b =>
                {
                    b.Property<int>("ProfessionSkillsId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("ProfessionSkillsId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProfessionSkill");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionSkills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProfessionId")
                        .HasColumnType("int");

                    b.Property<byte>("Quantity")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionId");

                    b.ToTable("ProfessionSkills");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalInformations")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<byte>("Agility")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Attacks")
                        .HasColumnType("tinyint");

                    b.Property<byte>("CloseCombat")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<byte>("Hitpoints")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<byte>("Inteligence")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Magic")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte>("Polish")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ProfessionLevel")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ProfessionRaceAllowed")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Resistance")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Shooting")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Speed")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Stamina")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Willpower")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Professions");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte>("SkillLevel")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Trait")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.Statistic", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsBasicValue")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCalculatedValue")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Statistics");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.AdditionalCharacterValue", b =>
                {
                    b.HasOne("WarhammerProfessionApp.Entities.Models.Character", "Character")
                        .WithMany("AdditionalValues")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.Character", b =>
                {
                    b.HasOne("WarhammerProfessionApp.Entities.Models.Profession", "CurrentProfession")
                        .WithMany()
                        .HasForeignKey("CurrentProfessionId");

                    b.HasOne("WarhammerProfessionApp.Entities.Models.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.CharacterAbility", b =>
                {
                    b.HasOne("WarhammerProfessionApp.Entities.Models.Ability", "Ability")
                        .WithMany("Characters")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarhammerProfessionApp.Entities.Models.Character", "Character")
                        .WithMany("Abilities")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.CharacterItem", b =>
                {
                    b.HasOne("WarhammerProfessionApp.Entities.Models.Character", "Character")
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarhammerProfessionApp.Entities.Models.Item", "Item")
                        .WithMany("Characters")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.CharacterProfession", b =>
                {
                    b.HasOne("WarhammerProfessionApp.Entities.Models.Character", "Character")
                        .WithMany("Professions")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarhammerProfessionApp.Entities.Models.Profession", "Profession")
                        .WithMany("Characters")
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.CharacterSkill", b =>
                {
                    b.HasOne("WarhammerProfessionApp.Entities.Models.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarhammerProfessionApp.Entities.Models.Skill", "Skill")
                        .WithMany("Characters")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.CharacterStatistic", b =>
                {
                    b.HasOne("WarhammerProfessionApp.Entities.Models.Character", "Character")
                        .WithMany("Statistics")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarhammerProfessionApp.Entities.Models.Statistic", "Statistic")
                        .WithMany("Characters")
                        .HasForeignKey("StatisticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.ExperienceAdditionalCharacterValue", b =>
                {
                    b.HasOne("WarhammerProfessionApp.Entities.Models.Character", "Character")
                        .WithMany("AdditionalExcerienceCostValues")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionAbilities", b =>
                {
                    b.HasOne("WarhammerProfessionApp.Entities.Models.Profession", "Profession")
                        .WithMany("Abilities")
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionAbility", b =>
                {
                    b.HasOne("WarhammerProfessionApp.Entities.Models.Ability", "Ability")
                        .WithMany("Professions")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionAbilities", "ProfessionAbilities")
                        .WithMany("Abilities")
                        .HasForeignKey("ProfessionAbilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionItem", b =>
                {
                    b.HasOne("WarhammerProfessionApp.Entities.Models.Item", "Item")
                        .WithMany("Professions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionItems", "ProfessionItems")
                        .WithMany("Items")
                        .HasForeignKey("ProfessionsItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionItems", b =>
                {
                    b.HasOne("WarhammerProfessionApp.Entities.Models.Profession", "Profession")
                        .WithMany("Equipment")
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionProfession", b =>
                {
                    b.HasOne("WarhammerProfessionApp.Entities.Models.Profession", "EntranceProfession")
                        .WithMany("OutputProfessions")
                        .HasForeignKey("EntranceProfessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarhammerProfessionApp.Entities.Models.Profession", "OutputProfession")
                        .WithMany("EntranceProfessions")
                        .HasForeignKey("OutputProfessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionSkill", b =>
                {
                    b.HasOne("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionSkills", "ProfessionSkills")
                        .WithMany("Skills")
                        .HasForeignKey("ProfessionSkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarhammerProfessionApp.Entities.Models.Skill", "Skill")
                        .WithMany("Professions")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.ManyToMany.ProfessionSkills", b =>
                {
                    b.HasOne("WarhammerProfessionApp.Entities.Models.Profession", "Profession")
                        .WithMany("Skills")
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarhammerProfessionApp.Entities.Models.Profession", b =>
                {
                    b.HasOne("WarhammerProfessionApp.Entities.Models.Image", "Image")
                        .WithMany("Professions")
                        .HasForeignKey("ImageId");
                });
#pragma warning restore 612, 618
        }
    }
}
